[pytest]
markers =
    api: marks api tests
    web: marks api tests
    android: marks android tests
    ios: marks ios tests

    smoke: marks smoke tests
    regression: marks regression tests

    positive: marks positive tests
    negative: marks negative tests

    login: marks login tests
    auth: marks auth tests
    product: marks product tests
    payment: marks payment tests
