from src import logger
from src.core.api.service.auth.model.api_auth import ApiAuth
from src.core.data.factory.common.data_item import DataItem


class ApiAuthFactory:
    """
    Factory for retrieving authentication objects.

    Provides a static method to fetch and log ApiAuth objects
    generated by a DataItem.
    """

    @staticmethod
    def get_api_auth(auth_data: DataItem) -> ApiAuth | None:
        """
        Retrieves an ApiAuth instance from the given data builder.
        :rtype: ApiAuth | None
        """
        api_auth = auth_data.get()
        if api_auth is None:
            logger.warning("AuthFactory returned None ApiAuth.")
        else:
            logger.info("Fetched ApiAuth: '%s'", api_auth)
        return api_auth
